# -*- mode: ruby -*-
# vi: set ft=ruby :

hostname = "mage.tkhamlai.com"
ip = "192.168.33.101"

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "trusty64"
    config.trigger.after [:destroy, :halt, :reload] do |trigger|
        trigger.run = {"path": "cleanup.sh"}
    end
    # Configure vagrant-cachier plugin
    if Vagrant.has_plugin?("vagrant-cachier")
     # Configure cached packages to be shared between instances of the same base box.
     # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
     config.cache.scope = :box
     config.cache.synced_folder_opts = {
       type: :nfs,
       # The nolock option can be useful for an NFSv3 client that wants to avoid the
       # NLM sideband protocol. Without this option, apt-get might hang if it tries 
       # to lock files needed for /var/cache/* operations. All of this can be avoided
       # by using NFSv4 everywhere. Please note that the tcp option is not the default.
       mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
     }
     # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
   end
   # @end: Configure vagrant-cachier plugin

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    # config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    # config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"

    # Provision
    config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.provision :reload
    config.vm.provision :shell, :run => 'always', :path => "provision.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # config.vm.network :forwarded_port, guest: 80, host: 8999
    # config.vm.network :forwarded_port, guest: 22, host: 2299

    # Synced folder
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs"
    config.vm.synced_folder "source", "/vagrant/source", id: "source", owner: "www-data", group: "www-data", create: true, mount_options: ["dmode=775", "fmode=664", "uid=33", "gid=33"], transient: false
    config.vm.synced_folder "public_html", "/var/www/html/magento/public_html", id: "public_html", owner: "www-data", group: "www-data", mount_options: ["dmode=775", "fmode=664", "uid=33", "gid=33"], transient: true
    config.vm.hostname = hostname
    config.vm.network :private_network, ip: ip

    # config.vm.synced_folder "../buffer/", "/home/vagrant/buffer/", id: "vagrant-root", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", nfs: true, mount_options: ["nolock", "async"], bsd__nfs_options: ["alldirs","async","nolock"]
    # config.nfs.map_uid = 0
    # config.nfs.map_gid = 0

    # VirtualBox settings
    config.vm.provider :virtualbox do |vb|
        # vb.customize ["modifyvm", :id, "--memory", "512"]
        # vb.customize ["modifyvm", :id, "--memory", "1024"]
        # vb.customize ["modifyvm", :id, "--memory", "2048"]
        # vb.customize ["modifyvm", :id, "--memory", "3072"]
        # vb.customize ["modifyvm", :id, "--memory", "4096"]
    end

    # VirtualBox setting
    # Use all CPU cores and 1/4 system memory
    config.vm.provider "virtualbox" do |v|
        host = RbConfig::CONFIG['host_os']

        # Give VM 1/8 system memory & access to all cpu cores on the host
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 8
        elsif host =~ /linux/
            cpus = `nproc`.to_i / 2
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
        else # sorry Windows folks, I can't help you
            cpus = 2
            mem = 1024
        end

        v.customize ["modifyvm", :id, "--memory", mem]
        v.customize ["modifyvm", :id, "--cpus", cpus]
    end

end